### ISSUE TITLE
Push 1.7.2 and 1.8 to Cocoapods Trunk

### ISSUE THREAD

**Issue by UberJason** [drewmccormack/ensembles#282]
Hey Drew! I noticed recently that you had a couple of releases (`1.7.2` in April 2018 and `1.8` just a couple weeks ago) which [haven't been pushed to Cocoapods trunk](https://github.com/CocoaPods/Specs/tree/master/Specs/b/d/c/Ensembles), meaning when we try to install Ensembles by Cocoapods, the system only sees `1.7.1` as the latest. Would you mind doing those quick `pod trunk push` commands to update the Cocoapods Spec repo?

**Comment by drewmccormack** [comment]
I wasn’t able to get it to push to cocoapods, I’m afraid. Was failing for some odd reason to do with SSZipArchive.

If you can get that working, I’m happy to push it.

Drew

**Comment by UberJason** [comment]
Funny you mentioned that - I tried pulling in the latest Ensembles directly from your GitHub URL, and I get an error in `CDEMultipeerCloudFileSystem.m`:

<img width="1012" alt="Screen Shot 2019-04-06 at 12 02 47 PM" src="https://user-images.githubusercontent.com/5779307/55672052-7ab27380-5864-11e9-8513-0e305103ec18.png">

I wonder if it's related?

**Comment by drewmccormack** [comment]
Yes, certainly related. SSZipArchive is a mess. It was a separate framework, now it is included in ZipArchive. But I can’t find a combination of imports/frameworks etc that seems to work.

Will take another look.

Drew

**Comment by drewmccormack** [comment]
Think this is now fixed. Should be updated in CocoaPods. 

Drew

**Comment by UberJason** [comment]
Looking great, thank you! I'm still having an issue with the Ensembles dyld not loading in my main project, but I think that's something up with my project setup in particular - when I create a new sample project and include Ensembles, everything is fine.

**Comment by drewmccormack** [comment]
Ensembles in CocoaPods is not using a dynamic library. It is static. 

The repo has a dynamic build option.

Drew

**Comment by UberJason** [comment]
Ensembles is not using a dynamic library, but I think Cocoapods makes it available as a dynamic library? I'm not sure - this stuff is over my head - but the error is `dyld: Library not loaded: ... reason: image not found`. It was working for me using Cocoapods 1.5.3, but not with 1.6.1, so I'm currently trying to isolate the issue and submit it to Cocoapods to see if I'm doing something bad that used to be tolerated and isn't anymore, or if it's a regression in Cocoapods.
